using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Blog.Shared.Helpers
{
    public class MimeType
    {
        public string Key { get; set; }
        public string Value { get; set; }
        public string Type { get; set; }
    }
    public class MimeTypeHelper
    {

        // private static IDictionary<string, string> _mapping = new Dictionary<string, string>(StringComparer.InvariantCultureIgnoreCase) {
        private static readonly List<MimeType> Mapping = new List<MimeType> { 
        #region Big freaking list of mime types

       new MimeType {Key = ".323", Value = "text/h323"},
       new MimeType {Key =".3g2",Value = "video/3gpp2"},
       new MimeType {Key =".3gp",Value = "video/3gpp"},
       new MimeType {Key =".3gp2",Value = "video/3gpp2"},
       new MimeType {Key =".3gpp",Value = "video/3gpp"},
       new MimeType {Key =".7z", Value ="application/x-7z-compressed"},
       new MimeType {Key =".aa",Value = "audio/audible"},
       new MimeType {Key =".AAC",Value = "audio/aac"},
       new MimeType {Key =".aaf", Value ="application/octet-stream"},
       new MimeType {Key =".aax",Value = "audio/vnd.audible.aax"},
       new MimeType {Key =".ac3", Value ="audio/ac3"},
       new MimeType {Key =".aca", Value ="application/octet-stream"},
       new MimeType {Key =".accda",Value = "application/msaccess.addin"},
       new MimeType {Key =".accdb", Value ="application/msaccess"},
       new MimeType {Key =".accdc", Value ="application/msaccess.cab"},
       new MimeType {Key =".accde",Value = "application/msaccess"},
       new MimeType {Key =".accdr",Value = "application/msaccess.runtime"},
       new MimeType {Key =".accdt", Value ="application/msaccess"},
       new MimeType {Key =".accdw",Value = "application/msaccess.webapplication"},
       new MimeType {Key =".accft",Value = "application/msaccess.ftemplate"},
       new MimeType {Key =".acx", Value ="application/internet-property-stream"},
       new MimeType {Key =".AddIn",Value ="text/xml"},
       new MimeType {Key =".ade", Value ="application/msaccess"},
       new MimeType {Key =".adobebridge",Value = "application/x-bridge-url"},
       new MimeType {Key =".adp",Value = "application/msaccess"},
       new MimeType {Key =".ADT",Value = "audio/vnd.dlna.adts"},
       new MimeType {Key =".ADTS",Value = "audio/aac"},
       new MimeType {Key =".afm", Value ="application/octet-stream"},
       new MimeType {Key =".ai", Value ="application/postscript"},
       new MimeType {Key =".aif",Value = "audio/x-aiff"},
       new MimeType {Key =".aifc",Value = "audio/aiff"},
       new MimeType {Key =".aiff",Value = "audio/aiff"},
       new MimeType {Key =".air", Value ="application/vnd.adobe.air-application-installer-package+zip"},
       new MimeType {Key =".amc",Value = "application/x-mpeg"},
       new MimeType {Key =".application",Value = "application/x-ms-application"},
       new MimeType {Key =".art", Value ="image/x-jg"},
       new MimeType {Key =".asa", Value ="application/xml"},
       new MimeType {Key =".asax",Value = "application/xml"},
       new MimeType {Key =".ascx",Value = "application/xml"},
       new MimeType {Key =".asd", Value ="application/octet-stream"},
       new MimeType {Key =".asf", Value ="video/x-ms-asf"},
       new MimeType {Key =".ashx",Value = "application/xml"},
       new MimeType {Key =".asi",Value = "application/octet-stream"},
       new MimeType {Key =".asm",Value = "text/plain"},
       new MimeType {Key =".asmx", Value ="application/xml"},
       new MimeType {Key =".aspx",Value = "application/xml"},
       new MimeType {Key =".asr", Value ="video/x-ms-asf"},
       new MimeType {Key =".asx",Value = "video/x-ms-asf"},
       new MimeType {Key =".atom",Value = "application/atom+xml"},
       new MimeType {Key =".au", Value ="audio/basic"},
       new MimeType {Key =".avi",Value = "video/x-msvideo"},
       new MimeType {Key =".axs",Value = "application/olescript"},
       new MimeType {Key =".bas",Value = "text/plain"},
       new MimeType {Key =".bcpio",Value = "application/x-bcpio"},
       new MimeType {Key =".bin", Value ="application/octet-stream"},
       new MimeType {Key =".bmp", Value ="image/bmp" ,Type = "Image"},
       new MimeType {Key =".c", Value ="text/plain"},
       new MimeType {Key =".cab",Value ="application/octet-stream"},
       new MimeType {Key =".caf", Value ="audio/x-caf"},
       new MimeType {Key =".calx",Value = "application/vnd.ms-office.calx"},
       new MimeType {Key =".cat", Value ="application/vnd.ms-pki.seccat"},
       new MimeType {Key =".cc", Value ="text/plain"},
       new MimeType {Key =".cd", Value ="text/plain"},
       new MimeType {Key =".cdda",Value = "audio/aiff"},
       new MimeType {Key =".cdf",Value = "application/x-cdf"},
       new MimeType {Key =".cer",Value = "application/x-x509-ca-cert"},
       new MimeType {Key =".chm", Value ="application/octet-stream"},
       new MimeType {Key =".class",Value = "application/x-java-applet"},
       new MimeType {Key =".clp", Value ="application/x-msclip"},
       new MimeType {Key =".cmx",Value = "image/x-cmx" ,Type = "Image"},
       new MimeType {Key =".cnf",Value = "text/plain"},
       new MimeType {Key =".cod", Value ="image/cis-cod" ,Type = "Image"},
       new MimeType {Key =".config",Value = "application/xml"},
       new MimeType {Key =".contact",Value = "text/x-ms-contact"},
       new MimeType {Key =".coverage",Value = "application/xml"},
       new MimeType {Key =".cpio", Value ="application/x-cpio"},
       new MimeType {Key =".cpp", Value ="text/plain"},
       new MimeType {Key =".crd",Value = "application/x-mscardfile"},
       new MimeType {Key =".crl", Value ="application/pkix-crl"},
       new MimeType {Key =".crt",Value = "application/x-x509-ca-cert"},
       new MimeType {Key =".cs", Value ="text/plain"},
       new MimeType {Key =".csdproj", Value ="text/plain"},
       new MimeType {Key =".csh", Value ="application/x-csh"},
       new MimeType {Key =".csproj",Value = "text/plain"},
       new MimeType {Key =".css", Value ="text/css"},
       new MimeType {Key =".csv", Value ="text/csv"},
       new MimeType {Key =".cur", Value ="application/octet-stream"},
       new MimeType {Key =".cxx", Value ="text/plain"},
       new MimeType {Key =".dat",Value = "application/octet-stream"},
       new MimeType {Key =".datasource",Value = "application/xml"},
       new MimeType {Key =".dbproj", Value ="text/plain"},
       new MimeType {Key =".dcr", Value ="application/x-director"},
       new MimeType {Key =".def",Value = "text/plain"},
       new MimeType {Key =".deploy",Value = "application/octet-stream"},
       new MimeType {Key =".der", Value ="application/x-x509-ca-cert"},
       new MimeType {Key =".dgml",Value = "application/xml"},
       new MimeType {Key =".dib",Value = "image/bmp" ,Type = "Image"},
       new MimeType {Key =".dif", Value ="video/x-dv"},
       new MimeType {Key =".dir",Value = "application/x-director"},
       new MimeType {Key =".disco",Value = "text/xml"},
       new MimeType {Key =".dll",Value = "application/x-msdownload"},
       new MimeType {Key =".dll.config",Value = "text/xml"},
       new MimeType {Key =".dlm", Value ="text/dlm"},
       new MimeType {Key =".doc", Value ="application/msword"},
       new MimeType {Key =".docm",Value = "application/vnd.ms-word.document.macroEnabled.12"},
       new MimeType {Key =".docx", Value ="application/vnd.openxmlformats-officedocument.wordprocessingml.document"},
       new MimeType {Key =".dot",Value = "application/msword"},
       new MimeType {Key =".dotm",Value = "application/vnd.ms-word.template.macroEnabled.12"},
       new MimeType {Key =".dotx", Value ="application/vnd.openxmlformats-officedocument.wordprocessingml.template"},
       new MimeType {Key =".dsp",Value = "application/octet-stream"},
       new MimeType {Key =".dsw",Value = "text/plain"},
       new MimeType {Key =".dtd", Value ="text/xml"},
       new MimeType {Key =".dtsConfig",Value = "text/xml"},
       new MimeType {Key =".dv", Value ="video/x-dv"},
       new MimeType {Key =".dvi", Value ="application/x-dvi"},
       new MimeType {Key =".dwf", Value ="drawing/x-dwf"},
       new MimeType {Key =".dwp", Value ="application/octet-stream"},
       new MimeType {Key =".dxr",Value = "application/x-director"},
       new MimeType {Key =".eml",Value = "message/rfc822"},
       new MimeType {Key =".emz",Value = "application/octet-stream"},
       new MimeType {Key =".eot",Value = "application/octet-stream"},
       new MimeType {Key =".eps", Value ="application/postscript"},
       new MimeType {Key =".etl",Value = "application/etl"},
       new MimeType {Key =".etx", Value ="text/x-setext"},
       new MimeType {Key =".evy",Value = "application/envoy"},
       new MimeType {Key =".exe",Value = "application/octet-stream"},
       new MimeType {Key =".exe.config", Value ="text/xml"},
       new MimeType {Key =".fdf", Value ="application/vnd.fdf"},
       new MimeType {Key =".fif", Value ="application/fractals"},
       new MimeType {Key =".filters",Value = "Application/xml"},
       new MimeType {Key =".fla",Value = "application/octet-stream"},
       new MimeType {Key =".flr",Value = "x-world/x-vrml"},
       new MimeType {Key =".flv", Value ="video/x-flv"},
       new MimeType {Key =".fsscript",Value = "application/fsharp-script"},
       new MimeType {Key =".fsx", Value ="application/fsharp-script"},
       new MimeType {Key =".generictest", Value ="application/xml"},
       new MimeType {Key =".gif",Value = "image/gif" ,Type = "Image"},
       new MimeType {Key =".group", Value ="text/x-ms-group"},
       new MimeType {Key =".gsm", Value ="audio/x-gsm"},
       new MimeType {Key =".gtar",Value = "application/x-gtar"},
       new MimeType {Key =".gz", Value ="application/x-gzip"},
       new MimeType {Key =".h",Value = "text/plain"},
       new MimeType {Key =".hdf",Value = "application/x-hdf"},
       new MimeType {Key =".hdml",Value = "text/x-hdml"},
       new MimeType {Key =".hhc",Value = "application/x-oleobject"},
       new MimeType {Key =".hhk", Value ="application/octet-stream"},
       new MimeType {Key =".hhp",Value = "application/octet-stream"},
       new MimeType {Key =".hlp", Value ="application/winhlp"},
       new MimeType {Key =".hpp",Value = "text/plain"},
       new MimeType {Key =".hqx",Value = "application/mac-binhex40"},
       new MimeType {Key =".hta", Value ="application/hta"},
       new MimeType {Key =".htc",Value = "text/x-component"},
       new MimeType {Key =".htm",Value = "text/html"},
       new MimeType {Key =".html",Value = "text/html"},
       new MimeType {Key =".htt", Value ="text/webviewhtml"},
       new MimeType {Key =".hxa",Value = "application/xml"},
       new MimeType {Key =".hxc", Value ="application/xml"},
       new MimeType {Key =".hxd",Value = "application/octet-stream"},
       new MimeType {Key =".hxe", Value ="application/xml"},
       new MimeType {Key =".hxf",Value = "application/xml"},
       new MimeType {Key =".hxh",Value = "application/octet-stream"},
       new MimeType {Key =".hxi", Value ="application/octet-stream"},
       new MimeType {Key =".hxk",Value = "application/xml"},
       new MimeType {Key =".hxq",Value = "application/octet-stream"},
       new MimeType {Key =".hxr", Value ="application/octet-stream"},
       new MimeType {Key =".hxs",Value = "application/octet-stream"},
       new MimeType {Key =".hxt", Value ="text/html"},
       new MimeType {Key =".hxv", Value ="application/xml"},
       new MimeType {Key =".hxw",Value = "application/octet-stream"},
       new MimeType {Key =".hxx", Value ="text/plain"},
       new MimeType {Key =".i", Value ="text/plain"},
       new MimeType {Key =".ico", Value ="image/x-icon" ,Type = "Image"},
       new MimeType {Key =".ics", Value ="application/octet-stream"},
       new MimeType {Key =".idl",Value = "text/plain"},
       new MimeType {Key =".ief", Value ="image/ief" ,Type = "Image"},
       new MimeType {Key =".iii", Value ="application/x-iphone"},
       new MimeType {Key =".inc",Value = "text/plain"},
       new MimeType {Key =".inf", Value ="application/octet-stream"},
       new MimeType {Key =".inl", Value ="text/plain"},
       new MimeType {Key =".ins", Value ="application/x-internet-signup"},
       new MimeType {Key =".ipa", Value ="application/x-itunes-ipa"},
       new MimeType {Key =".ipg",Value = "application/x-itunes-ipg"},
       new MimeType {Key =".ipproj", Value ="text/plain"},
       new MimeType {Key =".ipsw", Value ="application/x-itunes-ipsw"},
       new MimeType {Key =".iqy", Value ="text/x-ms-iqy"},
       new MimeType {Key =".isp", Value ="application/x-internet-signup"},
       new MimeType {Key =".ite", Value ="application/x-itunes-ite"},
       new MimeType {Key =".itlp", Value ="application/x-itunes-itlp"},
       new MimeType {Key =".itms",Value = "application/x-itunes-itms"},
       new MimeType {Key =".itpc",Value = "application/x-itunes-itpc"},
       new MimeType {Key =".IVF", Value ="video/x-ivf"},
       new MimeType {Key =".jar", Value ="application/java-archive"},
       new MimeType {Key =".java", Value ="application/octet-stream"},
       new MimeType {Key =".jck", Value ="application/liquidmotion"},
       new MimeType {Key =".jcz",Value = "application/liquidmotion"},
       new MimeType {Key =".jfif",Value = "image/pjpeg" ,Type = "Image"},
       new MimeType {Key =".jnlp",Value = "application/x-java-jnlp-file"},
       new MimeType {Key =".jpb", Value ="application/octet-stream"},
       new MimeType {Key =".jpe", Value ="image/jpeg" ,Type = "Image"},
       new MimeType {Key =".jpeg",Value = "image/jpeg" ,Type = "Image"},
       new MimeType {Key =".jpg",Value = "image/jpeg" ,Type = "Image"},
       new MimeType {Key =".js", Value ="application/x-javascript"},
       new MimeType {Key =".json", Value ="application/json"},
       new MimeType {Key =".jsx", Value ="text/jscript"},
       new MimeType {Key =".jsxbin",Value = "text/plain"},
       new MimeType {Key =".latex", Value ="application/x-latex"},
       new MimeType {Key =".library-ms",Value = "application/windows-library+xml"},
       new MimeType {Key =".lit", Value ="application/x-ms-reader"},
       new MimeType {Key =".loadtest",Value = "application/xml"},
       new MimeType {Key =".lpk", Value ="application/octet-stream"},
       new MimeType {Key =".lsf", Value ="video/x-la-asf"},
       new MimeType {Key =".lst", Value ="text/plain"},
       new MimeType {Key =".lsx", Value ="video/x-la-asf"},
       new MimeType {Key =".lzh",Value = "application/octet-stream"},
       new MimeType {Key =".m13",Value = "application/x-msmediaview"},
       new MimeType {Key =".m14", Value ="application/x-msmediaview"},
       new MimeType {Key =".m1v",Value = "video/mpeg"},
       new MimeType {Key =".m2t", Value ="video/vnd.dlna.mpeg-tts"},
       new MimeType {Key =".m2ts", Value ="video/vnd.dlna.mpeg-tts"},
       new MimeType {Key =".m2v",Value = "video/mpeg"},
       new MimeType {Key =".m3u", Value ="audio/x-mpegurl"},
       new MimeType {Key =".m3u8",Value = "audio/x-mpegurl"},
       new MimeType {Key =".m4a",Value = "audio/m4a"},
       new MimeType {Key =".m4b",Value = "audio/m4b"},
       new MimeType {Key =".m4p", Value ="audio/m4p"},
       new MimeType {Key =".m4r", Value ="audio/x-m4r"},
       new MimeType {Key =".m4v", Value ="video/x-m4v"},
       new MimeType {Key =".mac", Value ="image/x-macpaint" ,Type = "Image"},
       new MimeType {Key =".mak", Value ="text/plain"},
       new MimeType {Key =".man", Value ="application/x-troff-man"},
       new MimeType {Key =".manifest", Value ="application/x-ms-manifest"},
       new MimeType {Key =".map", Value ="text/plain"},
       new MimeType {Key =".master",Value = "application/xml"},
       new MimeType {Key =".mda", Value ="application/msaccess"},
       new MimeType {Key =".mdb", Value ="application/x-msaccess"},
       new MimeType {Key =".mde",Value = "application/msaccess"},
       new MimeType {Key =".mdp",Value = "application/octet-stream"},
       new MimeType {Key =".me", Value ="application/x-troff-me"},
       new MimeType {Key =".mfp",Value = "application/x-shockwave-flash"},
       new MimeType {Key =".mht", Value ="message/rfc822"},
       new MimeType {Key =".mhtml",Value = "message/rfc822"},
       new MimeType {Key =".mid",Value = "audio/mid"},
       new MimeType {Key =".midi",Value = "audio/mid"},
       new MimeType {Key =".mix",Value = "application/octet-stream"},
       new MimeType {Key =".mk", Value ="text/plain"},
       new MimeType {Key =".mmf", Value ="application/x-smaf"},
       new MimeType {Key =".mno",Value = "text/xml"},
       new MimeType {Key =".mny",Value = "application/x-msmoney"},
       new MimeType {Key =".mod",Value = "video/mpeg"},
       new MimeType {Key =".mov", Value ="video/quicktime"},
       new MimeType {Key =".movie", Value ="video/x-sgi-movie"},
       new MimeType {Key =".mp2", Value ="video/mpeg"},
       new MimeType {Key =".mp2v",Value = "video/mpeg"},
       new MimeType {Key =".mp3",Value = "audio/mpeg"},
       new MimeType {Key =".mp4",Value = "video/mp4"},
       new MimeType {Key =".mp4v",Value = "video/mp4"},
       new MimeType {Key =".mpa", Value ="video/mpeg"},
       new MimeType {Key =".mpe", Value ="video/mpeg"},
       new MimeType {Key =".mpeg", Value ="video/mpeg"},
       new MimeType {Key =".mpf",Value = "application/vnd.ms-mediapackage"},
       new MimeType {Key =".mpg",Value = "video/mpeg"},
       new MimeType {Key =".mpp",Value = "application/vnd.ms-project"},
       new MimeType {Key =".mpv2", Value ="video/mpeg"},
       new MimeType {Key =".mqv",Value = "video/quicktime"},
       new MimeType {Key =".ms", Value ="application/x-troff-ms"},
       new MimeType {Key =".msi", Value ="application/octet-stream"},
       new MimeType {Key =".mso",Value = "application/octet-stream"},
       new MimeType {Key =".mts", Value ="video/vnd.dlna.mpeg-tts"},
       new MimeType {Key =".mtx", Value ="application/xml"},
       new MimeType {Key =".mvb", Value ="application/x-msmediaview"},
       new MimeType {Key =".mvc", Value ="application/x-miva-compiled"},
       new MimeType {Key =".mxp",Value = "application/x-mmxp"},
       new MimeType {Key =".nc", Value ="application/x-netcdf"},
       new MimeType {Key =".nsc", Value ="video/x-ms-asf"},
       new MimeType {Key =".nws",Value = "message/rfc822"},
       new MimeType {Key =".ocx",Value = "application/octet-stream"},
       new MimeType {Key =".oda", Value ="application/oda"},
       new MimeType {Key =".odc", Value ="text/x-ms-odc"},
       new MimeType {Key =".odh", Value ="text/plain"},
       new MimeType {Key =".odl", Value ="text/plain"},
       new MimeType {Key =".odp",Value = "application/vnd.oasis.opendocument.presentation"},
       new MimeType {Key =".ods",Value = "application/oleobject"},
       new MimeType {Key =".odt", Value ="application/vnd.oasis.opendocument.text"},
       new MimeType {Key =".one",Value = "application/onenote"},
       new MimeType {Key =".onea",Value = "application/onenote"},
       new MimeType {Key =".onepkg",Value = "application/onenote"},
       new MimeType {Key =".onetmp",Value = "application/onenote"},
       new MimeType {Key =".onetoc", Value ="application/onenote"},
       new MimeType {Key =".onetoc2", Value ="application/onenote"},
       new MimeType {Key =".orderedtest", Value ="application/xml"},
       new MimeType {Key =".osdx", Value ="application/opensearchdescription+xml"},
       new MimeType {Key =".p10",Value = "application/pkcs10"},
       new MimeType {Key =".p12",Value = "application/x-pkcs12"},
       new MimeType {Key =".p7b",Value = "application/x-pkcs7-certificates"},
       new MimeType {Key =".p7c", Value ="application/pkcs7-mime"},
       new MimeType {Key =".p7m",Value = "application/pkcs7-mime"},
       new MimeType {Key =".p7r",Value = "application/x-pkcs7-certreqresp"},
       new MimeType {Key =".p7s",Value = "application/pkcs7-signature"},
       new MimeType {Key =".pbm",Value = "image/x-portable-bitmap" ,Type = "Image"},
       new MimeType {Key =".pcast", Value ="application/x-podcast"},
       new MimeType {Key =".pct", Value ="image/pict" ,Type = "Image"},
       new MimeType {Key =".pcx",Value = "application/octet-stream"},
       new MimeType {Key =".pcz",Value = "application/octet-stream"},
       new MimeType {Key =".pdf",Value = "application/pdf"},
       new MimeType {Key =".pfb", Value ="application/octet-stream"},
       new MimeType {Key =".pfm",Value = "application/octet-stream"},
       new MimeType {Key =".pfx",Value = "application/x-pkcs12"},
       new MimeType {Key =".pgm",Value = "image/x-portable-graymap" ,Type = "Image"},
       new MimeType {Key =".pic",Value = "image/pict" ,Type = "Image"},
       new MimeType {Key =".pict",Value = "image/pict" ,Type = "Image"},
       new MimeType {Key =".pkgdef", Value ="text/plain"},
       new MimeType {Key =".pkgundef",Value = "text/plain"},
       new MimeType {Key =".pko", Value ="application/vnd.ms-pki.pko"},
       new MimeType {Key =".pls", Value ="audio/scpls"},
       new MimeType {Key =".pma", Value ="application/x-perfmon"},
       new MimeType {Key =".pmc",Value = "application/x-perfmon"},
       new MimeType {Key =".pml",Value = "application/x-perfmon"},
       new MimeType {Key =".pmr", Value ="application/x-perfmon"},
       new MimeType {Key =".pmw",Value = "application/x-perfmon"},
       new MimeType {Key =".png", Value ="image/png" ,Type = "Image"},
       new MimeType {Key =".pnm",Value = "image/x-portable-anymap" ,Type = "Image"},
       new MimeType {Key =".pnt", Value ="image/x-macpaint" ,Type = "Image"},
       new MimeType {Key =".pntg",Value = "image/x-macpaint" ,Type = "Image"},
       new MimeType {Key =".pnz", Value ="image/png"},
       new MimeType {Key =".pot", Value ="application/vnd.ms-powerpoint"},
       new MimeType {Key =".potm",Value = "application/vnd.ms-powerpoint.template.macroEnabled.12"},
       new MimeType {Key =".potx", Value ="application/vnd.openxmlformats-officedocument.presentationml.template"},
       new MimeType {Key =".ppa", Value ="application/vnd.ms-powerpoint"},
       new MimeType {Key =".ppam",Value = "application/vnd.ms-powerpoint.addin.macroEnabled.12"},
       new MimeType {Key =".ppm",Value = "image/x-portable-pixmap" ,Type = "Image"},
       new MimeType {Key =".pps",Value ="application/vnd.ms-powerpoint"},
       new MimeType {Key =".ppsm",Value = "application/vnd.ms-powerpoint.slideshow.macroEnabled.12"},
       new MimeType {Key =".ppsx", Value ="application/vnd.openxmlformats-officedocument.presentationml.slideshow"},
       new MimeType {Key =".ppt", Value ="application/vnd.ms-powerpoint"},
       new MimeType {Key =".pptm",Value = "application/vnd.ms-powerpoint.presentation.macroEnabled.12"},
       new MimeType {Key =".pptx",Value = "application/vnd.openxmlformats-officedocument.presentationml.presentation"},
       new MimeType {Key =".prf", Value ="application/pics-rules"},
       new MimeType {Key =".prm", Value ="application/octet-stream"},
       new MimeType {Key =".prx",Value = "application/octet-stream"},
       new MimeType {Key =".ps", Value ="application/postscript"},
       new MimeType {Key =".psc1", Value ="application/PowerShell"},
       new MimeType {Key =".psd", Value ="application/octet-stream"},
       new MimeType {Key =".psess", Value ="application/xml"},
       new MimeType {Key =".psm", Value ="application/octet-stream"},
       new MimeType {Key =".psp",Value = "application/octet-stream"},
       new MimeType {Key =".pub", Value ="application/x-mspublisher"},
       new MimeType {Key =".pwz",Value = "application/vnd.ms-powerpoint"},
       new MimeType {Key =".qht",Value = "text/x-html-insertion"},
       new MimeType {Key =".qhtm",Value = "text/x-html-insertion"},
       new MimeType {Key =".qt", Value ="video/quicktime"},
       new MimeType {Key =".qti",Value = "image/x-quicktime" ,Type = "Image"},
       new MimeType {Key =".qtif",Value = "image/x-quicktime" ,Type = "Image"},
       new MimeType {Key =".qtl",Value = "application/x-quicktimeplayer"},
       new MimeType {Key =".qxd",Value = "application/octet-stream"},
       new MimeType {Key =".ra", Value ="audio/x-pn-realaudio"},
       new MimeType {Key =".ram", Value ="audio/x-pn-realaudio"},
       new MimeType {Key =".rar",Value = "application/octet-stream"},
       new MimeType {Key =".ras", Value ="image/x-cmu-raster" ,Type = "Image"},
       new MimeType {Key =".rat",Value = "application/rat-file"},
       new MimeType {Key =".rc", Value ="text/plain"},
       new MimeType {Key =".rc2", Value ="text/plain"},
       new MimeType {Key =".rct",Value = "text/plain"},
       new MimeType {Key =".rdlc",Value = "application/xml"},
       new MimeType {Key =".resx", Value ="application/xml"},
       new MimeType {Key =".rf", Value ="image/vnd.rn-realflash" ,Type = "Image"},
       new MimeType {Key =".rgb", Value ="image/x-rgb" ,Type = "Image"},
       new MimeType {Key =".rgs", Value ="text/plain"},
       new MimeType {Key =".rm", Value ="application/vnd.rn-realmedia"},
       new MimeType {Key =".rmi", Value ="audio/mid"},
       new MimeType {Key =".rmp",Value = "application/vnd.rn-rn_music_package"},
       new MimeType {Key =".roff", Value ="application/x-troff"},
       new MimeType {Key =".rpm", Value ="audio/x-pn-realaudio-plugin"},
       new MimeType {Key =".rqy", Value ="text/x-ms-rqy"},
       new MimeType {Key =".rtf", Value ="application/rtf"},
       new MimeType {Key =".rtx",Value = "text/richtext"},
       new MimeType {Key =".ruleset",Value = "application/xml"},
       new MimeType {Key =".s", Value ="text/plain"},
       new MimeType {Key =".safariextz",Value = "application/x-safari-safariextz"},
       new MimeType {Key =".scd", Value ="application/x-msschedule"},
       new MimeType {Key =".sct", Value ="text/scriptlet"},
       new MimeType {Key =".sd2",Value = "audio/x-sd2"},
       new MimeType {Key =".sdp", Value ="application/sdp"},
       new MimeType {Key =".sea", Value ="application/octet-stream"},
       new MimeType {Key =".searchConnector-ms",Value = "application/windows-search-connector+xml"},
       new MimeType {Key =".setpay", Value ="application/set-payment-initiation"},
       new MimeType {Key =".setreg", Value ="application/set-registration-initiation"},
       new MimeType {Key =".settings", Value ="application/xml"},
       new MimeType {Key =".sgimb", Value ="application/x-sgimb"},
       new MimeType {Key =".sgml",Value = "text/sgml"},
       new MimeType {Key =".sh",Value = "application/x-sh"},
       new MimeType {Key =".shar",Value = "application/x-shar"},
       new MimeType {Key =".shtml",Value = "text/html"},
       new MimeType {Key =".sit", Value ="application/x-stuffit"},
       new MimeType {Key =".sitemap",Value = "application/xml"},
       new MimeType {Key =".skin",Value = "application/xml"},
       new MimeType {Key =".sldm", Value ="application/vnd.ms-powerpoint.slide.macroEnabled.12"},
       new MimeType {Key =".sldx", Value ="application/vnd.openxmlformats-officedocument.presentationml.slide"},
       new MimeType {Key =".slk", Value ="application/vnd.ms-excel"},
       new MimeType {Key =".sln", Value ="text/plain"},
       new MimeType {Key =".slupkg-ms", Value ="application/x-ms-license"},
       new MimeType {Key =".smd",Value = "audio/x-smd"},
       new MimeType {Key =".smi",Value = "application/octet-stream"},
       new MimeType {Key =".smx",Value = "audio/x-smd"},
       new MimeType {Key =".smz",Value = "audio/x-smd"},
       new MimeType {Key =".snd", Value ="audio/basic"},
       new MimeType {Key =".snippet",Value = "application/xml"},
       new MimeType {Key =".snp",Value = "application/octet-stream"},
       new MimeType {Key =".sol", Value ="text/plain"},
       new MimeType {Key =".sor", Value ="text/plain"},
       new MimeType {Key =".spc",Value = "application/x-pkcs7-certificates"},
       new MimeType {Key =".spl", Value ="application/futuresplash"},
       new MimeType {Key =".src",Value = "application/x-wais-source"},
       new MimeType {Key =".srf",Value = "text/plain"},
       new MimeType {Key =".SSISDeploymentManifest", Value ="text/xml"},
       new MimeType {Key =".ssm",Value = "application/streamingmedia"},
       new MimeType {Key =".sst", Value ="application/vnd.ms-pki.certstore"},
       new MimeType {Key =".stl",Value = "application/vnd.ms-pki.stl"},
       new MimeType {Key =".sv4cpio", Value ="application/x-sv4cpio"},
       new MimeType {Key =".sv4crc", Value ="application/x-sv4crc"},
       new MimeType {Key =".svc", Value ="application/xml"},
       new MimeType {Key =".swf",Value = "application/x-shockwave-flash"},
       new MimeType {Key =".t", Value ="application/x-troff"},
       new MimeType {Key =".tar",Value = "application/x-tar"},
       new MimeType {Key =".tcl", Value ="application/x-tcl"},
       new MimeType {Key =".testrunconfig",Value = "application/xml"},
       new MimeType {Key =".testsettings",Value = "application/xml"},
       new MimeType {Key =".tex", Value ="application/x-tex"},
       new MimeType {Key =".texi",Value = "application/x-texinfo"},
       new MimeType {Key =".texinfo", Value ="application/x-texinfo"},
       new MimeType {Key =".tgz", Value ="application/x-compressed"},
       new MimeType {Key =".thmx", Value ="application/vnd.ms-officetheme"},
       new MimeType {Key =".thn",Value = "application/octet-stream"},
       new MimeType {Key =".tif", Value ="image/tiff" ,Type = "Image"},
       new MimeType {Key =".tiff",Value = "image/tiff" ,Type = "Image"},
       new MimeType {Key =".tlh", Value ="text/plain"},
       new MimeType {Key =".tli", Value ="text/plain"},
       new MimeType {Key =".toc", Value ="application/octet-stream"},
       new MimeType {Key =".tr", Value ="application/x-troff"},
       new MimeType {Key =".trm",Value = "application/x-msterminal"},
       new MimeType {Key =".trx", Value ="application/xml"},
       new MimeType {Key =".ts", Value ="video/vnd.dlna.mpeg-tts"},
       new MimeType {Key =".tsv",Value = "text/tab-separated-values"},
       new MimeType {Key =".ttf", Value ="application/octet-stream"},
       new MimeType {Key =".tts", Value ="video/vnd.dlna.mpeg-tts"},
       new MimeType {Key =".txt", Value ="text/plain"},
       new MimeType {Key =".u32",Value = "application/octet-stream"},
       new MimeType {Key =".uls", Value ="text/iuls"},
       new MimeType {Key =".user", Value ="text/plain"},
       new MimeType {Key =".ustar", Value ="application/x-ustar"},
       new MimeType {Key =".vb",Value = "text/plain"},
       new MimeType {Key =".vbdproj", Value ="text/plain"},
       new MimeType {Key =".vbk", Value ="video/mpeg"},
       new MimeType {Key =".vbproj", Value ="text/plain"},
       new MimeType {Key =".vbs",Value = "text/vbscript"},
       new MimeType {Key =".vcf", Value ="text/x-vcard"},
       new MimeType {Key =".vcproj", Value ="Application/xml"},
       new MimeType {Key =".vcs", Value ="text/plain"},
       new MimeType {Key =".vcxproj",Value = "Application/xml"},
       new MimeType {Key =".vddproj", Value ="text/plain"},
       new MimeType {Key =".vdp",Value = "text/plain"},
       new MimeType {Key =".vdproj", Value ="text/plain"},
       new MimeType {Key =".vdx", Value ="application/vnd.ms-visio.viewer"},
       new MimeType {Key =".vml", Value ="text/xml"},
       new MimeType {Key =".vscontent",Value = "application/xml"},
       new MimeType {Key =".vsct", Value ="text/xml"},
       new MimeType {Key =".vsd",Value = "application/vnd.visio"},
       new MimeType {Key =".vsi", Value ="application/ms-vsi"},
       new MimeType {Key =".vsix",Value = "application/vsix"},
       new MimeType {Key =".vsixlangpack",Value = "text/xml"},
       new MimeType {Key =".vsixmanifest",Value = "text/xml"},
       new MimeType {Key =".vsmdi", Value ="application/xml"},
       new MimeType {Key =".vspscc", Value ="text/plain"},
       new MimeType {Key =".vss", Value ="application/vnd.visio"},
       new MimeType {Key =".vsscc",Value = "text/plain"},
       new MimeType {Key =".vssettings",Value = "text/xml"},
       new MimeType {Key =".vssscc",Value = "text/plain"},
       new MimeType {Key =".vst",Value = "application/vnd.visio"},
       new MimeType {Key =".vstemplate", Value ="text/xml"},
       new MimeType {Key =".vsto", Value ="application/x-ms-vsto"},
       new MimeType {Key =".vsw", Value ="application/vnd.visio"},
       new MimeType {Key =".vsx",Value = "application/vnd.visio"},
       new MimeType {Key =".vtx", Value ="application/vnd.visio"},
       new MimeType {Key =".wav", Value ="audio/wav"},
       new MimeType {Key =".wave",Value = "audio/wav"},
       new MimeType {Key =".wax",Value = "audio/x-ms-wax"},
       new MimeType {Key =".wbk", Value ="application/msword"},
       new MimeType {Key =".wbmp",Value = "image/vnd.wap.wbmp" ,Type = "Image"},
       new MimeType {Key =".wcm", Value ="application/vnd.ms-works"},
       new MimeType {Key =".wdb", Value ="application/vnd.ms-works"},
       new MimeType {Key =".wdp", Value ="image/vnd.ms-photo" ,Type = "Image"},
       new MimeType {Key =".webarchive", Value ="application/x-safari-webarchive"},
       new MimeType {Key =".webtest", Value ="application/xml"},
       new MimeType {Key =".wiq",Value = "application/xml"},
       new MimeType {Key =".wiz",Value = "application/msword"},
       new MimeType {Key =".wks",Value = "application/vnd.ms-works"},
       new MimeType {Key =".WLMP",Value = "application/wlmoviemaker"},
       new MimeType {Key =".wlpginstall",Value = "application/x-wlpg-detect"},
       new MimeType {Key =".wlpginstall3",Value = "application/x-wlpg3-detect"},
       new MimeType {Key =".wm", Value ="video/x-ms-wm"},
       new MimeType {Key =".wma",Value = "audio/x-ms-wma"},
       new MimeType {Key =".wmd",Value = "application/x-ms-wmd"},
       new MimeType {Key =".wmf", Value ="application/x-msmetafile"},
       new MimeType {Key =".wml", Value ="text/vnd.wap.wml"},
       new MimeType {Key =".wmlc", Value ="application/vnd.wap.wmlc"},
       new MimeType {Key =".wmls", Value ="text/vnd.wap.wmlscript"},
       new MimeType {Key =".wmlsc",Value = "application/vnd.wap.wmlscriptc"},
       new MimeType {Key =".wmp",Value = "video/x-ms-wmp"},
       new MimeType {Key =".wmv", Value ="video/x-ms-wmv"},
       new MimeType {Key =".wmx",Value = "video/x-ms-wmx"},
       new MimeType {Key =".wmz", Value ="application/x-ms-wmz"},
       new MimeType {Key =".wpl", Value ="application/vnd.ms-wpl"},
       new MimeType {Key =".wps",Value = "application/vnd.ms-works"},
       new MimeType {Key =".wri", Value ="application/x-mswrite"},
       new MimeType {Key =".wrl", Value ="x-world/x-vrml"},
       new MimeType {Key =".wrz",Value = "x-world/x-vrml"},
       new MimeType {Key =".wsc", Value ="text/scriptlet"},
       new MimeType {Key =".wsdl", Value ="text/xml"},
       new MimeType {Key =".wvx",Value = "video/x-ms-wvx"},
       new MimeType {Key =".x", Value ="application/directx"},
       new MimeType {Key =".xaf",Value = "x-world/x-vrml"},
       new MimeType {Key =".xaml", Value ="application/xaml+xml"},
       new MimeType {Key =".xap", Value ="application/x-silverlight-app"},
       new MimeType {Key =".xbap",Value = "application/x-ms-xbap"},
       new MimeType {Key =".xbm", Value ="image/x-xbitmap" ,Type = "Image"},
       new MimeType {Key =".xdr",Value = "text/plain"},
       new MimeType {Key =".xht",Value = "application/xhtml+xml"},
       new MimeType {Key =".xhtml", Value ="application/xhtml+xml"},
       new MimeType {Key =".xla",Value = "application/vnd.ms-excel"},
       new MimeType {Key =".xlam",Value = "application/vnd.ms-excel.addin.macroEnabled.12"},
       new MimeType {Key =".xlc", Value ="application/vnd.ms-excel"},
       new MimeType {Key =".xld",Value = "application/vnd.ms-excel"},
       new MimeType {Key =".xlk", Value ="application/vnd.ms-excel"},
       new MimeType {Key =".xll", Value ="application/vnd.ms-excel"},
       new MimeType {Key =".xlm", Value ="application/vnd.ms-excel"},
       new MimeType {Key =".xls",Value = "application/vnd.ms-excel"},
       new MimeType {Key =".xlsb", Value ="application/vnd.ms-excel.sheet.binary.macroEnabled.12"},
       new MimeType {Key =".xlsm", Value ="application/vnd.ms-excel.sheet.macroEnabled.12"},
       new MimeType {Key =".xlsx", Value ="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
       new MimeType {Key =".xlt", Value ="application/vnd.ms-excel"},
       new MimeType {Key =".xltm", Value ="application/vnd.ms-excel.template.macroEnabled.12"},
       new MimeType {Key =".xltx",Value = "application/vnd.openxmlformats-officedocument.spreadsheetml.template"},
       new MimeType {Key =".xlw", Value ="application/vnd.ms-excel"},
       new MimeType {Key =".xml",Value = "text/xml"},
       new MimeType {Key =".xmta", Value ="application/xml"},
       new MimeType {Key =".xof", Value ="x-world/x-vrml"},
       new MimeType {Key =".XOML", Value ="text/plain"},
       new MimeType {Key =".xpm", Value ="image/x-xpixmap" ,Type = "Image"},
       new MimeType {Key =".xps", Value ="application/vnd.ms-xpsdocument"},
       new MimeType {Key =".xrm-ms", Value ="text/xml"},
       new MimeType {Key =".xsc", Value ="application/xml"},
       new MimeType {Key =".xsd",Value = "text/xml"},
       new MimeType {Key =".xsf", Value ="text/xml"},
       new MimeType {Key =".xsl", Value ="text/xml"},
       new MimeType {Key =".xslt",Value = "text/xml"},
       new MimeType {Key =".xsn",Value = "application/octet-stream"},
       new MimeType {Key =".xss", Value ="application/xml"},
       new MimeType {Key =".xtp", Value ="application/octet-stream"},
       new MimeType {Key =".xwd",Value = "image/x-xwindowdump" ,Type = "Image"},
       new MimeType {Key =".z", Value ="application/x-compress"},
       new MimeType {Key =".zip", Value ="application/x-zip-compressed"},
       new MimeType {Key =".zip", Value ="application/zip"},
       new MimeType {Key =".zip", Value ="application/zip-compressed"},
       new MimeType {Key =".zip", Value ="multipart/x-zip"},
       new MimeType {Key =".zip", Value ="application/octet-stream"},
        #endregion
        };

        #region Methods
        public static string GetMimeType(string extension)
        {
            if (extension == null)
            {
                throw new ArgumentNullException(nameof(extension));
            }

            if (!extension.StartsWith("."))
            {
                extension = "." + extension;
            }

            foreach (var mapping in Mapping.Where(mapping => mapping.Key.Equals(extension)))
            {
                return mapping.Value;
            }
            return "application/octet-stream";
            //return _mappings.TryGetValue(extension, out var mime) ? mime : "application/octet-stream";
        }
        public static List<string> GetExtensions()
        {
            return Mapping.Select(c => c.Key).ToList();
        }
        public static List<string> GetMimeTypes()
        {
            return Mapping.Select(c => c.Value).ToList();
        }

        public static List<MimeType> GetImageMimeTypeValues()
        {
            return Mapping.Where(c => c.Type.Equals("Image")).ToList();
        }
        #endregion

    }
}
